# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from phyai_gateway.bindings import (
    model_inference_pb2 as phyai__gateway_dot_bindings_dot_model__inference__pb2,
)

GRPC_GENERATED_VERSION = "1.73.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in phyai_gateway/bindings/model_inference_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ModelInferenceStub(object):
    """Model-defined inference requests forwarded by the gateway."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
            "/robot.inference.v1.ModelInference/Infer",
            request_serializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.InferenceRequest.SerializeToString,
            response_deserializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.InferenceResponse.FromString,
            _registered_method=True,
        )


class ModelInferenceServicer(object):
    """Model-defined inference requests forwarded by the gateway."""

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ModelInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Infer": grpc.unary_unary_rpc_method_handler(
            servicer.Infer,
            request_deserializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.InferenceRequest.FromString,
            response_serializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.InferenceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "robot.inference.v1.ModelInference", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "robot.inference.v1.ModelInference", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ModelInference(object):
    """Model-defined inference requests forwarded by the gateway."""

    @staticmethod
    def Infer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/robot.inference.v1.ModelInference/Infer",
            phyai__gateway_dot_bindings_dot_model__inference__pb2.InferenceRequest.SerializeToString,
            phyai__gateway_dot_bindings_dot_model__inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class ModelRegistryStub(object):
    """Model servers register an endpoint and renew it with heartbeats."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
            "/robot.inference.v1.ModelRegistry/Register",
            request_serializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.RegisterRequest.SerializeToString,
            response_deserializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.RegisterResponse.FromString,
            _registered_method=True,
        )
        self.Heartbeat = channel.unary_unary(
            "/robot.inference.v1.ModelRegistry/Heartbeat",
            request_serializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.HeartbeatRequest.SerializeToString,
            response_deserializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.HeartbeatResponse.FromString,
            _registered_method=True,
        )


class ModelRegistryServicer(object):
    """Model servers register an endpoint and renew it with heartbeats."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ModelRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.RegisterRequest.FromString,
            response_serializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.RegisterResponse.SerializeToString,
        ),
        "Heartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.Heartbeat,
            request_deserializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.HeartbeatRequest.FromString,
            response_serializer=phyai__gateway_dot_bindings_dot_model__inference__pb2.HeartbeatResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "robot.inference.v1.ModelRegistry", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "robot.inference.v1.ModelRegistry", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ModelRegistry(object):
    """Model servers register an endpoint and renew it with heartbeats."""

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/robot.inference.v1.ModelRegistry/Register",
            phyai__gateway_dot_bindings_dot_model__inference__pb2.RegisterRequest.SerializeToString,
            phyai__gateway_dot_bindings_dot_model__inference__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Heartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/robot.inference.v1.ModelRegistry/Heartbeat",
            phyai__gateway_dot_bindings_dot_model__inference__pb2.HeartbeatRequest.SerializeToString,
            phyai__gateway_dot_bindings_dot_model__inference__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
