"""PhyAI pi0.5 policy execution, independent of a particular robot.

The adapter supplies preprocessed tensors; the policy owns the engine and a
seeded CPU noise stream. Keeping engine setup here leaves deployment entry
points responsible only for composing a robot, an adapter, and a control loop.
"""

from __future__ import annotations

from typing import Any
from pathlib import Path
from threading import Lock, Event
from dataclasses import replace, dataclass

from omegaconf import MISSING

from .configuration import repository_path


def _validate_num_inference_steps(value: int | None) -> None:
    """Accept a positive Euler-step count, or None to preserve the checkpoint.

    Reject bool explicitly because it is an int subclass in Python. This guard
    also covers callers that construct a policy directly without the YAML parser.
    """
    if value is not None and (type(value) is not int or value < 1):
        raise ValueError(
            "policy.num_inference_steps must be a positive integer or null"
        )


@dataclass
class Pi05PolicyConfig:
    """Local pi0.5 checkpoint and PhyAI engine settings, independent of a robot."""

    # Required local export directory, resolved relative to the checkout root.
    # MISSING lets --print-config show the template without inventing a default.
    checkpoint: str = MISSING
    # Operator-level kernel selection is kept separate from model weights.
    kernel_policy: str = "examples/deployment/configs/pi05_bf16.yaml"
    # Seed one CPU generator per policy; do not reseed before every prediction.
    seed: int = 42
    # Flow-matching Euler updates per prediction, not the 50-target action horizon.
    # None preserves the checkpoint's setting. An override requires a new engine
    # because its time embeddings and CUDA graph depend on the step count.
    num_inference_steps: int | None = None
    # Capture/replay is an engine optimization, not a different action schedule.
    use_cuda_graph: bool = True
    # CPU runtime threads; this does not configure ROS executors or control_hz.
    num_threads: int = 16

    def validate(self) -> None:
        """Check local paths and engine arguments without allocating GPU resources."""
        _validate_num_inference_steps(self.num_inference_steps)
        if self.num_threads < 1:
            raise ValueError("policy.num_threads must be positive")
        if not 0 <= self.seed < 2**64:
            raise ValueError("policy.seed must be in [0, 2**64)")
        if not self.checkpoint.strip() or not repository_path(self.checkpoint).is_dir():
            raise ValueError(
                "policy.checkpoint must name an existing checkpoint directory"
            )
        if (
            not self.kernel_policy.strip()
            or not repository_path(self.kernel_policy).is_file()
        ):
            raise ValueError(
                "policy.kernel_policy must name an existing kernel YAML file"
            )


@dataclass(frozen=True)
class Pi05PolicyRequest:
    """One preprocessed snapshot; diffusion noise is generated by the policy.

    processed is the PI05Processor output: pixel_values has shape
    (1, camera_count, 3, image_size, image_size), input_ids has shape
    (1, token_count), and lang_lens has shape (1,). The normalized robot state
    and instruction are already encoded in the tokens by the adapter's processor.
    Keeping this boundary free of ROS messages lets the same policy serve other
    robots whose adapters produce the same model inputs.
    """

    processed: Any


class Pi05Policy:
    """Own a BF16 PhyAI engine and a reproducible stream of diffusion noise.

    The deployment worker calls predict synchronously. This class does not read
    sensors, maintain an action queue, interpolate commands, or publish to ROS.
    A lock serializes access to the engine, its graph buffers, and the generator.
    close may run on the shutdown thread while predict is still active; an event
    defers engine destruction until that prediction releases its resources.
    """

    def __init__(
        self,
        checkpoint: Path,
        *,
        kernel_policy: Path,
        seed: int = 42,
        num_inference_steps: int | None = None,
        use_cuda_graph: bool = True,
        num_threads: int = 16,
    ) -> None:
        """Load one local pi0.5 engine with batch size one.

        Checkpoint configuration supplies chunk length, padded action dimension,
        and model settings. num_inference_steps optionally replaces only the
        flow-matching Euler-step count before engine construction. kernel_policy
        selects implementations; seed, use_cuda_graph, and num_threads control
        this runtime instance. Heavy imports are delayed until construction, so
        configuration inspection needs neither an initialized CUDA engine nor
        model weights in memory.
        """
        _validate_num_inference_steps(num_inference_steps)
        import torch
        from phyai.utils import load_config
        from phyai.engine_config import DeviceConfig, EngineConfig, RuntimeConfig
        from phyai.kernel.config import KernelConfig
        from phyai.models.pi05.main_pi05 import PI05Args
        from phyai.models.pi05.scheduler_pi05 import PI05Request
        from phyai.models.pi05.configuration_pi05 import PI05Config

        from phyai import Engine, EngineArgs

        config = load_config(checkpoint, PI05Config)
        if num_inference_steps is not None:
            # PI05Config is frozen. Replace only the Euler-step count, retaining
            # all checkpoint architecture settings and leaving config.json alone.
            # The plugin builds its time-embedding table and captures a loop of N
            # steps with dt=-1/N; changing N after Engine(...) would be too late.
            config = replace(config, num_inference_steps=num_inference_steps)
        self._num_inference_steps = int(config.num_inference_steps)
        self._torch = torch
        self._request_type = PI05Request
        self._chunk_size = int(config.chunk_size)
        self._max_action_dim = int(config.max_action_dim)
        # CPU noise avoids coupling this stream to the engine's CUDA RNG state.
        # Reproducibility is per call sequence, including the discarded warmup.
        self._generator = torch.Generator().manual_seed(seed)
        # Pass the resolved model config through the plugin's existing API so
        # the override reaches setup/capture rather than being overwritten by a
        # second checkpoint load. BF16 kernels, graph selection, and padded action
        # dimensions are otherwise unchanged. No general engine code is patched.
        self._engine = Engine(
            EngineArgs(
                plugin="pi05",
                plugin_args=PI05Args(
                    checkpoint_dir=checkpoint, config=config, max_batch_size=1
                ),
                config=EngineConfig(
                    device=DeviceConfig(target="cuda", params_dtype=torch.bfloat16),
                    runtime=RuntimeConfig(
                        use_cuda_graph=use_cuda_graph, num_threads=num_threads
                    ),
                    kernel=KernelConfig(config_path=str(kernel_policy)),
                ),
            )
        )
        self._lock = Lock()
        self._close_requested = Event()
        self._closed = False

    @property
    def num_inference_steps(self) -> int:
        """Resolved, startup-only Euler-step count used by this engine instance.

        Exposed for logging rather than mutation: changing the schedule requires
        rebuilding the policy so time embeddings and graph capture stay aligned.
        """
        return self._num_inference_steps

    def predict(self, request: Pi05PolicyRequest) -> Any:
        """Return normalized actions shaped (1, chunk_size, max_action_dim).

        The returned tensor is detached float32 on CPU. It still includes the
        model's padded action coordinates; the adapter slices, unnormalizes, and
        interprets them using the observation paired with this request.
        Engine errors propagate to RobotDeployment's failure/stop handling.
        """
        with self._lock:
            if self._close_requested.is_set():
                raise RuntimeError("Pi05Policy is closed")
            try:
                # Draw fresh initial diffusion noise for the entire prediction,
                # not just the execution prefix. Prefix selection happens later.
                noise = self._torch.randn(
                    1,
                    self._chunk_size,
                    self._max_action_dim,
                    generator=self._generator,
                    dtype=self._torch.float32,
                )
                processed = request.processed
                with self._torch.inference_mode():
                    # Detach output from any reusable CUDA-graph buffers before
                    # returning it to adapter postprocessing.
                    return (
                        self._engine.step(
                            self._request_type(
                                pixel_values=processed.pixel_values,
                                input_ids=processed.input_ids,
                                lang_lens=processed.lang_lens,
                                noise=noise,
                            )
                        )
                        .detach()
                        .float()
                        .cpu()
                    )
            finally:
                # Shutdown can time out waiting for inference. The worker that
                # still holds the lock must then release the engine itself,
                # including when engine.step raises rather than returns.
                if self._close_requested.is_set():
                    self._close_engine()

    def _close_engine(self) -> None:
        """Release the engine once; the caller must already hold self._lock."""
        if not self._closed:
            self._engine.close()
            self._closed = True

    def close(self) -> None:
        """Do not destroy CUDA resources underneath a timed-out predictor.

        Hardware is stopped before this call. If inference is still active,
        the worker releases its own engine in predict's finally block.
        """
        # Set the event before attempting the lock so no later predict call can
        # start. A nonblocking acquire avoids extending hardware-shutdown waits.
        self._close_requested.set()
        if self._lock.acquire(blocking=False):
            try:
                self._close_engine()
            finally:
                self._lock.release()
